### ISSUE TITLE
Add more algorithm support

### ISSUE THREAD

**Issue by x24thkk** [usdAG/cstc#127]
Can support for SM2, SM3, and SM4 be added?

**Comment by fhaag95** [comment]
Hi :wave: 
Thanks for your request! We're looking into it. I'll update the issue soon with more information.

**Comment by fhaag95** [comment]
Short update: We evaluated the algorithms and will add it to our backlog for the next release which is coming soon. As soon as it's available on the develop branch I'll update you here and you can provide us with feedback, if possible.

**Comment by x24thkk** [comment]
Looking forward to it!

**Comment by fhaag95** [comment]
Hi, sorry for the delay, we integrated the algorithms in the CSTC on the develop branch. Feel free to test the modules and provide us with feedback if applicable! We look forward to hearing from you :+1:

**Comment by x24thkk** [comment]
Hi, I am very happy to use this new funct. I am already using it and it can be used normally. Thank you very much.
