### ISSUE TITLE
JSON extractor cannot handle complex JSON structures

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#130]
Hi,

The JSON extractor can only handle simple values, but not more complex structures. It is also not very intuitive to use.

Given the following JSON:

```json
{
    "abc": {
        "def": {
            "ghi": "jkl",
            "mno": "pqr"
        },
        "stu": {
            "vwx": "yza",
            "bcd": "efg"
        }
    }
}
```

If i want to have the abc.def-Subtree and specify "abc.def" for the extractor, i get the error message "JSON data of unknown type." which is not very descriptive. In fact the extractor does only seem  to be able to extract single values, eg. "abc.def.ghi" works and returns the value "jkl".

1. It would be nice to be able to extract whole subtrees with the extractor instead of only single values.
2. It would be good to add a remark about the syntax to the help message. Even finding out that the syntax to retrieve an element is "abc.def.ghi" did take me a moment because it is not intuitive.

**Comment by fhaag95** [comment]
Hi, thanks for reaching out. This functionality was up to now not supported by the operation. As it's really useful we implemented it on the develop branch and it will be ready in the next release of the CSTC soon.
