### ISSUE TITLE
Request feature: AES encryption PKCS7 padding

### ISSUE THREAD

**Issue by Henry1601** [usdAG/cstc#166]
Hi team, I found this extension is extremely useful and helpful for me in performing transformation for requests and responses in Burp.

However, I'm in a case where the AES encryption requires PKCS7 padding and CSTC has not yet supported this type of padding.

![image](https://github.com/user-attachments/assets/a12e4773-9f1d-4df6-ae98-5fc9c2e42fcd)

It would be great if your team could implement this feature in future releases. Thanks and have a nice day!

**Comment by fhaag95** [comment]
Hi :wave: 
Thanks for the feedback, we'll be looking into it! I'll keep you updated :+1:

**Comment by fhaag95** [comment]
Short update on that topic. We took a look at the implementation of the operation and it uses the `java.crypto.Cipher` implementation. For this implementation selecting PKCS5 Padding internally uses PKCS7 already. Could you try decrypting a padded ciphertext with the PKCS5 Padding? In our internal tests it seemed to work.

**Comment by Henry1601** [comment]
Hi @fhaag95,
Sorry for the late reply!
I've tried to decrypt a padded ciphertext with PKCS5 Padding and it's working well. Thanks a lot for your support and I'll keep you updated if there are any issues regarding this in the future.
Appreciate.

**Comment by fhaag95** [comment]
Nice, that's coherent with our testing so far. We'll integrate a change to address the differences in naming in the module.

**Comment by fhaag95** [comment]
Hey, we integrated the change into the develop branch already. In the next release the change will be effective. Thanks for reaching out and helping improve the CSTC :+1:
