### ISSUE TITLE
Need rsa implementation

### ISSUE THREAD

**Issue by Margular** [usdAG/cstc#18]
need rsa implementation

**Comment by qtc-de** [comment]
Could you please specify some more details what you need and how it should look like?

**Comment by Margular** [comment]
The same as aes except that the algorithm is rsa, because I encountered a situation where the client is encrypted with rsa. At this time, if the plugin implements rsa, you can easily modify the content.

**Comment by qtc-de** [comment]
Ah okay, I think I get your point. So the operation should take a public key on the file system and use it for encryption? There are several ways to do this. Have to check how to implement it in a generic way, but I guess it can (and will) be done.

**Comment by Margular** [comment]
Thank you very much, I think a lot of people need this feature

**Comment by qtc-de** [comment]
Implemented on the develop branch. However, not really tested in depth. If you encounter any problems, just report them ;)

**Comment by qtc-de** [comment]
Was merged to master
