### ISSUE TITLE
From_HTML_Entity function

### ISSUE THREAD

**Issue by theblackturtle** [usdAG/cstc#19]
Hi, It will be nice if it has `From_HTML_Entity` function because sometimes you need to decode JSON embed in HTML response.

**Comment by qtc-de** [comment]
Could you please specify some more details what you need and how it should look like?

**Comment by theblackturtle** [comment]
Hi @qtc-de, This is an exam: https://gchq.github.io/CyberChef/#recipe=From_HTML_Entity()&input=dGhpcyZhcG9zO3MgYW4gZXhhbXBsZQomcXVvdDsKJmFtcDs

**Comment by qtc-de** [comment]
Ah okay, this is rather straight forward. Will be implemented soon ;)

**Comment by qtc-de** [comment]
Implemented in the develop branch.

But notice that there seems to be no good library to perform HTML transformations on byte input. This means that the HTTP input needs to be translated to a string first. Fist causes no problems for 99% of the applications out there. However, if an application uses raw-bytes inside of HTTP requests, this may causes problems.

We try to keep all operations *byte safe* (no unintended transformations on raw bytes), but like already said library support is missing here. The preferred way to resolve this in future would be, that Burp exposes its ``HTML Encode`` and ``HTML Decode`` operations as part of their extender API. But currently it is not available.

Issue will be closed after the next push to master.

**Comment by qtc-de** [comment]
Was merged to master
