### ISSUE TITLE
AES Decryption Problem

### ISSUE THREAD

**Issue by abdilahrf** [usdAG/cstc#3]
Hi there,

I am trying to use AES Decryption with ECB Mode but the problem is i cannot leave the IV Field to empty and for ECB Mode it doesn't require IV I dont know if there already workaround for this

![image](https://user-images.githubusercontent.com/6015012/70023262-76904e80-15c9-11ea-92ad-4f816a409322.png)

**Comment by qtc-de** [comment]
Issue is fixed on the development branch. However, notice that there is a general problem how cstc operates on raw bytes (see issue #4 for more details). Encryption and Decryption should work fine for cstc internally, but external apps might get problems with the encoding. We will fix that soon. 

Thanks for Reporting :)
