### ISSUE TITLE
CSTC and Binary content modification

### ISSUE THREAD

**Issue by Himself132** [usdAG/cstc#33]
Hello - in reference to https://github.com/usdAG/cstc/issues/32 - I'm just opening another ticket.

CSTC is modifying binary content for situations like file uploads.

I confirmed that my user options were set to raw.  There are no project options that have this option, either way it accomplishes the same thing I'd imagine not sure if that was a clerical error on your part or I'm blind.  I am on kali linux and have it set to display raw bytes now to confirm and did previously during my first encounter of the problem (restored the project and associated settings).

To reproduce I'd recommend using an upstream proxy (I just chained two burp instances together) so you can see the before and after tab and confirm that it isn't what you are viewing but it is what is actually being sent.  That's how I verified what i saw after showing the display being different.

**Comment by qtc-de** [comment]
Hi, sorry for the late reply but I finally found time to work on this.

Unfortunately, I cannot reproduce your issue. Here is an example, where I sent a binary *ELF* file to a server as part of a *HTTP POST* request. To make sure that *CSTC* is processing the request, I used the ``String.Replace`` module to replace the String ``ELF`` with ``UFF``. The following screenshots show that there is no modification of the binary content:

**Non CSTC:**
![non-cstc](https://user-images.githubusercontent.com/49147108/97872083-b69a0d00-1d15-11eb-95f7-036a73d58165.png)

**CSTC:**
![cstc](https://user-images.githubusercontent.com/49147108/97872110-c3b6fc00-1d15-11eb-995a-ccbe04846920.png)

I even implemented a small python server to verify the checksum of the file that arrives on the server side. They are always identical and no unintended modifications are made by *CSTC*. 

I can imagine that the cause of your problems is one of the following:

1. You use an outdated version of *CSTC* (raw-byte safe operations were first implemented in [Version v1.0.0](https://github.com/usdAG/cstc/releases/tag/v1.0.0))
2. You used a raw-byte incompatible operation (e.g. regex search and replace is not byte compatible, as raw byte content is first *UTF-8* encoded before the matching. During this process, non *UTF-8* conform characters are encoded as [UTF8-Replacement Character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character))
3. Your user options are incorrect, but this should of course not be the case as you explicitly mentioned this.

![user-options](https://user-images.githubusercontent.com/49147108/97872774-e39aef80-1d16-11eb-99c1-da40a1bc4eb5.png)

I could imagine that point 2 is the most likely cause for your issue :thinking:

**Comment by Himself132** [comment]
Hello - thank you for the research but I think there are still issues here.

1. Is not the case - I install it via the Burp Store which i have confirmed keeps your extension up to date.
2. What do you need from me to reproduce in a way that shows that this modification is happening? What kind of proof? A video or something of that nature?  I am not doing any operations as you've described.  I am merely sending files from a raw byte origin of another burp instance, proxying it through another Burp instance and having CSTC interact with it.
3. My kali instances default to this, and as I mentioned previously, i double checked that burp state and settings and it was raw bytes

**Comment by qtc-de** [comment]
Wow, time is really flying. Sorry again for the late response. Other were recently too time consuming that I forgot about this issue. I think a Video is not required, but something that I can reproduce would be nice. At least a screenshot from your receipt pane. Ideal also a ``curl`` command or whatever you use for the upload.

With this information, I can just load the same receipt into my Burp, use your request command and hopefully can reproduce your issue :)

**Comment by Himself132** [comment]
No worries on the timing, I'm hoping you can return the favor as I will need some time to setup a testbed and retest.

**Comment by Himself132** [comment]
In the extremely low chance that this comes up again I'll provide those  details sorry for the delays
