### ISSUE TITLE
Add setter for multipart/form-data parameters

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#39]
Using version 1.2.1, straight form the BApp store.

There does not currently seem to be a setter for parameters in a multipart/form-data request. Setting those parameters in another way e. g. with string replace is possible, but unnecessarily complicated and brittle. Having a dedicated setter for this would be nice.

**Comment by qtc-de** [comment]
Should be doable. The Burp Extender API supports the ``PARAM_MULTIPART_ATTR`` attribute within the ``IParameter`` interface. I guess we can implement this in the same way as for the GetSetter and PostSetter. As soon as we find time, we will look into this :)

**Comment by fhaag95** [comment]
Feature was implemented in the meantime and will be available in the next release.
