### ISSUE TITLE
UI-Enhancement for the filter window

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#40]
Using version 1.2.1 from the BApp store.

CSTC uses the filter window to determine, which Burp tools the transformations are applied to:

![filter_1](https://user-images.githubusercontent.com/78096618/106018796-37249b80-60c2-11eb-965d-3fa9c57f9132.png)

Currently, there are kind of two different filter windows: the filters for incoming and outgoing traffic have to be set separately by first selecting the tab for incoming or outgoing traffic in the upper left corner of the screen (see next screenshot) and then selecting the filter button.

![filter_2](https://user-images.githubusercontent.com/78096618/106018822-3e4ba980-60c2-11eb-9d98-5577960f2360.png)

At least for me, this is not very intuitive and it is easy to forget. I think it would be better to have a single filter window where the policy can be set for traffic in both directions.

**Comment by qtc-de** [comment]
I agree that it can be a pitfall, but it also adds more flexibility. In some situations you may want exactly this behavior. E.g. when having two complicated recipes in both chains and suddenly want only outgoing traffic to be modified. In this case, you can just disable the incoming chain, without having to clear it.

I understand your point, but in my world, flexibility is the more important thing.

**Comment by LMRupp** [comment]
Sorry, that wasn't well worded.

It is good that the user can define separate filters for input and output, this issue is about the UI. Currently, if the user has selected the input, he can set filters only for the input. If the user has selected the output, he can select filters only for the output direction. I would like for the user to be able to see and edit the current filters for input and output separately from each other, but in the same window. The function of the feature would stay the same, but it would be easier and more intuitive to use if there was just one window to set all the filters.

**Comment by qtc-de** [comment]
Ah... Okay, I understand. This sounds good to me. We will work on this soon :)

**Comment by fhaag95** [comment]
This enhancement was also implemented in the meantime and will be included in the next release of the CSTC
