### ISSUE TITLE
Operation state not saved/restored when re-opening Burp

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#45]
Using version 1.2.1 from the BApp Store

How to reproduce:
1. create a recipe and disable some of the operations
2. close and re-open Burp
3. the previously disabled operations are enabled now

**Comment by qtc-de** [comment]
Thanks for the report. We will look into this soon.

**Comment by fhaag95** [comment]
The corresponding Pull Request (https://github.com/usdAG/cstc/pull/53) was merged into the develop branch. The issue will be fixed in the next release of the CSTC. Thanks again for reporting!
