### ISSUE TITLE
Encoding issues with raw data

### ISSUE THREAD

**Issue by qtc-de** [usdAG/cstc#5]
AS @mschader already mentioned in pull request #4 the handling of raw data (not UTF-8 encoded) is flawed in the current cstc implementation. If raw data is send to cstc, it gets modified automatically by Java due to some superfluous string transformations.

Pull #4 should fix this for the initial part of the cstc workflow, but also all plugins should be checked for this behavior. Furthermore, it should be verified that changes on the encoding (like pull request #4) do not break other functionality.

**Comment by mschader** [comment]
The result of a transformed input (after baking the receipt) has in some cases the same issue. There is an if block which leads to this part:

https://github.com/usdAG/cstc/blob/23eb27942d8490918b98eef5123be04aeda966de/src/de/usd/cstchef/view/RecipePanel.java#L402-L411

So the result will be casted to a new string and upon copying it to the array, it calls .getBytes(), which again will lead to a malformed result if the input only consisted of raw data.

**Comment by qtc-de** [comment]
List of affected operations that need to be modified.

**Data Format:**
- [ ] Url encode
- [ ] Url decode

**Extractors: **

- [x] Regex (Wont Fix)
- [ ] HTTP URI
- [ ] HTTP POST Parameter
- [ ] HTTP GET Parameter
- [ ] HTTP Method
- [ ] HTTP Header

**String:**

- [ ] Replace
- [ ] Static String
- [ ] Substring

**Comment by qtc-de** [comment]
As described in pull-request #11, this issue is basically implemented and fixed. We will close this for now and open smaller issues for places, where cstc is still not working correctly with raw bytes.
