### ISSUE TITLE
Compatibility with the dark burp theme

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#55]
CSTC does not work well together with the dark burp theme. For example, sometimes if you drag operations on the operation lane, those operations will be invisible if the dark theme is used. While it is documented that there might be issues with the dark theme (see known issues), i think this problem should be fixed.

**Comment by fhaag95** [comment]
Thanks for your request. The bug with invisibility could not be reproduced, but we are aware of some layout issues. We are working on that for the new release :+1:

**Comment by fhaag95** [comment]
We are compatible with the dark theme of Burp as far as we can see. Feel free to test against the develop branch and comment if you encounter further issues. Thanks!
